-- AlterTable
ALTER TABLE "Group" ADD COLUMN     "entryFee" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN     "pricePerKwh" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "budget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "isAdmin" BOOLEAN NOT NULL DEFAULT false;
